### ISSUE TITLE
UserLocal有类似的界面

### ISSUE THREAD

**Issue by MiracleXYZ** [kagaya85/DDCalendar#1]
这个功能好像和UserLocal的[时间表](http://virtual-youtuber.userlocal.jp/schedules)很像……他们很可能是收集人工填写的表单。

如果自动化做成了也是很棒的😂

**Comment by kagaya85** [comment]
哇，这是个好东西，之前一直考虑数据来源的问题，如果这个网站更新及时的话也可以考虑直接从这里抓取数据。
十分感谢😀

**Comment by MiracleXYZ** [comment]
这个更新还是比较及时的，不过由于是人工填写，很可能出现错误，爬取的时候还是要注意一下的。
